### ISSUE TITLE
Please expand comment to include where/how the .csv is generated.

### ISSUE THREAD

**Issue by dmcmanam** [mskcc/igo-lims-plugins#15]
https://github.com/mskcc/igo-lims-plugins/blob/9f115bf04c38333acc4982e30ee315d837834399/src/main/java/com/velox/sloan/cmo/workflows/digitalpcr/DigitalPcrResultsParser.java#L17

**Comment by apatruno618** [comment]
The csv is generated by the Biorad instrument
