### ISSUE TITLE
Eliminate igoOnSave plugin

### ISSUE THREAD

**Issue by apatruno618** [mskcc/igo-lims-plugins#54]
The igoOnSave plugin runs on every change to the DB including during sample submission and promote. Since those limsRest endpoints take so long to return a response the browser often sends a duplicate request and the app times out before the user is notified that the submission/promotion was successful. This also causes delays in other web apps that depend on limsRest because its busy waiting on the igoOnSave to complete.

Recent issues are documented in Teamwork:
[https://mskcc.teamwork.com/#/tasks/27860288](url)
[https://mskcc.teamwork.com/#/tasks/27880659](url)
unable to log into Sample QC or Run QC

The plan is to eliminate deprecated logic and move any logic that we still need to more relevant locations.

https://github.com/mskcc/igo-lims-plugins/blob/master/src/main/java/com/velox/sloan/cmo/workflows/General/IgoOnSavePlugin.java

More details in [https://mskcc.teamwork.com/#/tasks/27873309](url)

- [x] Delete logic for updating Request.DateModified
- [x] Move updateRemainingReadsToSequence(rec) to UpdateLimsSampleLevelQcTask in LimsRest
- [x] Move mapHumanPercentageFromDdpcrResultsToDnaQcReport(theSavedRecords) to https://github.com/mskcc/igo-lims-plugins/blob/ac124531caa80adab1338e55875db467641b8d79/src/main/java/com/velox/sloan/cmo/workflows/digitalpcr/DigitalPcrReportGenerator.java#L291
- [x] Move validateSampleFields(rec, dtTypeName) into its own plugin to be executed in the `Create New Lab Process for Samples` and `Assign Lab Process to Samples` workflows. This is estimated to affect 3562 sample records created <= 2020
- [x] Delete validateCmoInfoDataTypeFields(rec, dtTypeName) as IGO will no longer support this validation

**Comment by FahimehMirhaj** [comment]
The code changes in the igo-lims-plugins can be found in [this](https://github.com/mskcc/igo-lims-plugins/pull/56) PR.
